linters:
  enable:
    - revive

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: unhandled-error
        arguments:
          - "fmt.Printf"