name: Test and coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -skip TestIntegrationTestSuite ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  lint:
    golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
          with:
            go-version: 1.21
            cache: false
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54